const $=s=>document.querySelector(s);const $$=s=>document.querySelectorAll(s);
$('#closeNotice').onclick=()=>$('.announcement').remove();
$('#mobileMenu').onclick=()=>$('#mainNav').classList.toggle('open');
const modal=$('#loginModal');let selectedRole='buyer';
$('#openLogin').onclick=()=>modal.classList.add('open');$('#closeLogin').onclick=()=>modal.classList.remove('open');modal.onclick=e=>{if(e.target===modal)modal.classList.remove('open')};
$$('.role-options button').forEach(btn=>btn.onclick=()=>{$$('.role-options button').forEach(x=>x.classList.remove('selected'));btn.classList.add('selected');selectedRole=btn.dataset.role});
$('#loginAction').onclick=()=>{modal.classList.remove('open');openDashboard(selectedRole)};
const dashboard=$('#dashboard');
const data={buyer:{label:'BUYER PORTAL',title:'Good morning, Alex.',user:'Alex Smith',nav:['Overview','My orders','Request for quote','Wishlist','Messages','Account settings'],kpis:[['Orders this month','12','+18% from last month'],['Open quotes','04','2 awaiting replies'],['Saved products','28','+6 this month'],['Reward balance','$84.20','Available cashback']]},seller:{label:'SELLER PORTAL',title:'Welcome back, Nordic Home.',user:'Nordic Home Co.',nav:['Overview','Products','Orders','Quotes & messages','Customers','Payouts','Store settings'],kpis:[['Gross sales','$24,680','+24.8% from last month'],['Orders','184','+12.4% this month'],['Products live','126','8 drafts'],['Store rating','4.9 / 5','98% positive reviews']]},admin:{label:'ADMIN CONSOLE',title:'Marketplace overview.',user:'WE Market Admin',nav:['Overview','Sellers','Products','Orders & refunds','Customers','Payouts','Reports','Settings'],kpis:[['GMV this month','$284,920','+21.4% from last month'],['Active sellers','842','18 pending approval'],['Total orders','3,482','+16.7% this month'],['Platform revenue','$28,492','10% marketplace fee']]}};
function openDashboard(role){const d=data[role];dashboard.classList.add('active');$('#portalLabel').textContent=d.label;$('#dashTitle').textContent=d.title;$('#dashUser').textContent=d.user;const nav=$('#dashboardNav');nav.innerHTML=d.nav.map((x,i)=>`<button class="${i?'':'active'}">${x}</button>`).join('');$('#dashboardContent').innerHTML=`<div class="dash-kpis">${d.kpis.map(k=>`<div class="kpi"><small>${k[0]}</small><strong>${k[1]}</strong><span class="positive">↗ ${k[2]}</span></div>`).join('')}</div><div class="dashboard-grid"><div class="dash-card"><h3>Sales overview <small style="float:right;color:#8ca451;font-size:10px">Last 30 days⌄</small></h3><div class="bar-chart">${[38,55,42,75,58,90,64,48,79,66,92,73].map(h=>`<i style="height:${h}%"></i>`).join('')}</div></div><div class="dash-card"><h3>${role==='admin'?'Marketplace activity':role==='seller'?'Store health':'Recent activity'}</h3><div class="activity"><div><span>✓</span><p><b>${role==='seller'?'New order #WM-10482':'Order #WM-10482 delivered'}</b><small>Today · 2 hours ago</small></p></div><div><span>✦</span><p><b>${role==='admin'?'New seller application':'Quote response received'}</b><small>Yesterday · 10:24 AM</small></p></div><div><span>↗</span><p><b>${role==='admin'?'Product flagged for review':'Payment successfully processed'}</b><small>Yesterday · 8:41 AM</small></p></div></div></div></div><div class="dash-card" style="margin-top:16px"><h3>${role==='admin'?'Seller applications':'Recent orders'} <a href="#" style="float:right;color:#85a549;font-size:10px">View all →</a></h3><table class="dash-table"><thead><tr><th>${role==='admin'?'SELLER':'ORDER'}</th><th>DATE</th><th>AMOUNT</th><th>STATUS</th></tr></thead><tbody><tr><td><b>${role==='admin'?'Mori Atelier':'#WM-10482'}</b><br><small style="color:#93a099">${role==='admin'?'Japan · Fashion':'Stoneware table set'}</small></td><td>Sep 28, 2026</td><td>$${role==='admin'?'—':'128.00'}</td><td><span class="status">${role==='admin'?'Review':'Delivered'}</span></td></tr><tr><td><b>${role==='admin'?'Apex Supply Ltd.':'#WM-10476'}</b><br><small style="color:#93a099">${role==='admin'?'UK · Business supplies':'Wireless audio dock'}</small></td><td>Sep 27, 2026</td><td>$${role==='admin'?'—':'68.50'}</td><td><span class="status">${role==='admin'?'Approved':'Processing'}</span></td></tr></tbody></table></div>`;$$('#dashboardNav button').forEach(b=>b.onclick=()=>{ $$('#dashboardNav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#dashTitle').textContent=b.textContent==='Overview'?d.title:b.textContent+' · '+d.label.toLowerCase()});}
$('#logout').onclick=()=>dashboard.classList.remove('active');$('#mobileDash').onclick=()=>$('.dashboard-sidebar').classList.toggle('open');
$$('.add').forEach(btn=>btn.onclick=()=>{btn.textContent='Added ✓';btn.style.color='#172321';setTimeout(()=>btn.textContent='Add to cart +',1400)});
